export const COLORS_ADD_REQUEST = 'COLORS_ADD_REQUEST'
export const COLORS_ADD_SUCCESS = 'COLORS_ADD_SUCCESS'
export const COLORS_ADD_FAIL = 'COLORS_ADD_FAIL'

export const GET_ALL_COLORS_REQUEST = 'GET_ALL_COLORS_REQUEST'
export const GET_ALL_COLORS_SUCCESS = 'GET_ALL_COLORS_SUCCESS'
export const GET_ALL_COLORS_FAIL = 'GET_ALL_COLORS_FAIL'


export const COLORS_UPDATE_REQUEST = 'COLORS_UPDATE_REQUEST'
export const COLORS_UPDATE_SUCCESS = 'COLORS_UPDATE_SUCCESS'
export const COLORS_UPDATE_FAIL = 'COLORS_UPDATE_FAIL'

export const COLORS_DELETE_REQUEST = 'COLORS_DELETE_REQUEST'
export const COLORS_DELETE_SUCCESS = 'COLORS_DELETE_SUCCESS'
export const COLORS_DELETE_FAIL = 'COLORS_DELETE_FAIL'
