export const COUNT_ADD_REQUEST = 'COUNT_ADD_REQUEST'
export const COUNT_ADD_SUCCESS = 'COUNT_ADD_SUCCESS'
export const COUNT_ADD_FAIL = 'COUNT_ADD_FAIL'

export const GET_ALL_COUNT_REQUEST = 'GET_ALL_COUNT_REQUEST'
export const GET_ALL_COUNT_SUCCESS = 'GET_ALL_COUNT_SUCCESS'
export const GET_ALL_COUNT_FAIL = 'GET_ALL_COUNT_FAIL'

export const COUNT_UPDATE_REQUEST = 'COUNT_UPDATE_REQUEST'
export const COUNT_UPDATE_SUCCESS = 'COUNT_UPDATE_SUCCESS'
export const COUNT_UPDATE_FAIL = 'COUNT_UPDATE_FAIL'

export const COUNT_DELETE_REQUEST = 'COUNT_DELETE_REQUEST'
export const COUNT_DELETE_SUCCESS = 'COUNT_DELETE_SUCCESS'
export const COUNT_DELETE_FAIL = 'COUNT_DELETE_FAIL'
