export const COUNT_ADD_REQUEST = 'COUNT_ADD_REQUEST'
export const COUNT_ADD_SUCCESS = 'COUNT_ADD_SUCCESS'
export const COUNT_ADD_FAIL = 'COUNT_ADD_FAIL'

export const GET_ALL_COUNT_REQUEST = 'GET_ALL_COUNT_REQUEST'
export const GET_ALL_COUNT_SUCCESS = 'GET_ALL_COUNT_SUCCESS'
export const GET_ALL_COUNT_FAIL = 'GET_ALL_COUNT_FAIL'
