export const FORM_ADD_REQUEST = 'FORM_ADD_REQUEST'
export const FORM_ADD_SUCCESS = 'FORM_ADD_SUCCESS'
export const FORM_ADD_FAIL = 'FORM_ADD_FAIL'

export const GET_ALL_FORM_REQUEST = 'GET_ALL_FORM_REQUEST'
export const GET_ALL_FORM_SUCCESS = 'GET_ALL_FORM_SUCCESS'
export const GET_ALL_FORM_FAIL = 'GET_ALL_FORM_FAIL'
