export const FORMULA_ADD_REQUEST = 'FORMULA_ADD_REQUEST'
export const FORMULA_ADD_SUCCESS = 'FORMULA_ADD_SUCCESS'
export const FORMULA_ADD_FAIL = 'FORMULA_ADD_FAIL'

export const GET_ALL_FORMULA_REQUEST = 'GET_ALL_FORMULA_REQUEST'
export const GET_ALL_FORMULA_SUCCESS = 'GET_ALL_FORMULA_SUCCESS'
export const GET_ALL_FORMULA_FAIL = 'GET_ALL_FORMULA_FAIL'
