export const FORMULA_ADD_REQUEST = 'FORMULA_ADD_REQUEST'
export const FORMULA_ADD_SUCCESS = 'FORMULA_ADD_SUCCESS'
export const FORMULA_ADD_FAIL = 'FORMULA_ADD_FAIL'

export const GET_ALL_FORMULA_REQUEST = 'GET_ALL_FORMULA_REQUEST'
export const GET_ALL_FORMULA_SUCCESS = 'GET_ALL_FORMULA_SUCCESS'
export const GET_ALL_FORMULA_FAIL = 'GET_ALL_FORMULA_FAIL'

export const FORMULA_UPDATE_REQUEST = 'FORMULA_UPDATE_REQUEST'
export const FORMULA_UPDATE_SUCCESS = 'FORMULA_UPDATE_SUCCESS'
export const FORMULA_UPDATE_FAIL = 'FORMULA_UPDATE_FAIL'

export const FORMULA_DELETE_REQUEST = 'FORMULA_DELETE_REQUEST'
export const FORMULA_DELETE_SUCCESS = 'FORMULA_DELETE_SUCCESS'
export const FORMULA_DELETE_FAIL = 'FORMULA_DELETE_FAIL'
