export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const DETAILS_ORDER_REQUEST = 'DETAILS_ORDER_REQUEST'
export const DETAILS_ORDER_SUCCESS = 'DETAILS_ORDER_SUCCESS'
export const DETAILS_ORDER_FAIL = 'DETAILS_ORDER_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'