export const SERVICES_ADD_REQUEST = 'SERVICES_ADD_REQUEST'
export const SERVICES_ADD_SUCCESS = 'SERVICES_ADD_SUCCESS'
export const SERVICES_ADD_FAIL = 'SERVICES_ADD_FAIL'

export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST'
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS'
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL'
