export const SERVICES_ADD_REQUEST = 'SERVICES_ADD_REQUEST'
export const SERVICES_ADD_SUCCESS = 'SERVICES_ADD_SUCCESS'
export const SERVICES_ADD_FAIL = 'SERVICES_ADD_FAIL'

export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST'
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS'
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL'

export const SERVICES_UPDATE_REQUEST = 'SERVICES_UPDATE_REQUEST'
export const SERVICES_UPDATE_SUCCESS = 'SERVICES_UPDATE_SUCCESS'
export const SERVICES_UPDATE_FAIL = 'SERVICES_UPDATE_FAIL'

export const SERVICES_DELETE_REQUEST = 'SERVICES_DELETE_REQUEST'
export const SERVICES_DELETE_SUCCESS = 'SERVICES_DELETE_SUCCESS'
export const SERVICES_DELETE_FAIL = 'SERVICES_DELETE_FAIL'
