export const TECHNIC_ADD_REQUEST = 'TECHNIC_ADD_REQUEST'
export const TECHNIC_ADD_SUCCESS = 'TECHNIC_ADD_SUCCESS'
export const TECHNIC_ADD_FAIL = 'TECHNIC_ADD_FAIL'

export const GET_ALL_TECHNIC_REQUEST = 'GET_ALL_TECHNIC_REQUEST'
export const GET_ALL_TECHNIC_SUCCESS = 'GET_ALL_TECHNIC_SUCCESS'
export const GET_ALL_TECHNIC_FAIL = 'GET_ALL_TECHNIC_FAIL'
