export const TECHNIC_ADD_REQUEST = 'TECHNIC_ADD_REQUEST'
export const TECHNIC_ADD_SUCCESS = 'TECHNIC_ADD_SUCCESS'
export const TECHNIC_ADD_FAIL = 'TECHNIC_ADD_FAIL'

export const GET_ALL_TECHNIC_REQUEST = 'GET_ALL_TECHNIC_REQUEST'
export const GET_ALL_TECHNIC_SUCCESS = 'GET_ALL_TECHNIC_SUCCESS'
export const GET_ALL_TECHNIC_FAIL = 'GET_ALL_TECHNIC_FAIL'

export const TECHNIC_UPDATE_REQUEST = 'TECHNIC_UPDATE_REQUEST'
export const TECHNIC_UPDATE_SUCCESS = 'TECHNIC_UPDATE_SUCCESS'
export const TECHNIC_UPDATE_FAIL = 'TECHNIC_UPDATE_FAIL'

export const TECHNIC_DELETE_REQUEST = 'TECHNIC_DELETE_REQUEST'
export const TECHNIC_DELETE_SUCCESS = 'TECHNIC_DELETE_SUCCESS'
export const TECHNIC_DELETE_FAIL = 'TECHNIC_DELETE_FAIL'
